phrase:
  access_token: 6dbf0ef122174de1bb051954e508451366ae1dd8fcca86b133bdf089f44eed1a
  project_id: ea917e939d025669b071fe428f584a19
  push:
    sources:
    - file: ./en.json
      params:
        file_format: simple_json
        locale_id: English #Can be the name (e.g. en-US) or public id (via Language settings -> API) of the locale. Preferred is the public id.
        update_translations: true #Indicates whether existing translations should be updated with the file content.
  pull:
    targets:
    - file: ./ar.json
      params:
        file_format: simple_json
        locale_id: Arabic #Can be the name (e.g. en-US) or public id (via Language settings -> API) of the locale. Preferred is the public id.
        include_empty_translations: true #Indicates whether keys without translations should be included in the output as well.
